swagger: "2.4.15"
info:
  title: Task Managment API
  description: API to create, delete end edit Tasks.
  version: 1.0.0
host: localhost
basePath: /
schemes:
  - http

paths:
  /boards:
    post:
      operationId: createBoard
      summary: Creates a new board.
      consumes:
        - application/json
      parameters:
        - in: body
          name: board
          description: The board to create.
          schema:
            $ref: '#/definitions/Board'
      responses:
        201:
          description: Created
    get:
      operationId: getAllBoards
      summary: Get list of boards.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: A list of Boards
          schema:
            type: array
            items:
              $ref: '#/definitions/Board'
    delete:
      operationId: deleteBoard
      summary: Delete board.
      produces:
        - application/json
      parameters:
        - in: body
          name: board
          description: The board to delete.
          schema:
            $ref: '#/definitions/Board'
      responses:
        200:
          description: Deleted
    put:
      operationId: editBoard
      summary: Edit board.
      produces:
        - application/json
      parameters:
        - in: body
          name: board
          description: The board with changes.
          schema:
            $ref: '#/definitions/Board'
      responses:
        200:
          description: Edited

  /columns:
    post:
      operationId: createColumn
      summary: Creates a new column.
      consumes:
        - application/json
      parameters:
        - in: body
          name: column
          description: The column to create.
          schema:
            $ref: '#/definitions/Column'
      responses:
        201:
          description: Created.
    get:
      operationId: getAllColumns
      summary: Get list of columns.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: A list of Columns
          schema:
            type: array
            items:
              $ref: '#/definitions/Column'
    delete:
      operationId: deleteColumn
      summary: Delete column.
      produces:
        - application/json
      parameters:
        - in: body
          name: column
          description: The column to delete.
          schema:
            $ref: '#/definitions/Column'
      responses:
        200:
          description: Deleted
    put:
      operationId: editColumn
      summary: Edit column.
      produces:
        - application/json
      parameters:
        - in: body
          name: column
          description: The column with changes.
          schema:
            $ref: '#/definitions/Column'
      responses:
        200:
          description: Edited.

  /tasks:
    post:
      operationId: createTask
      summary: Creates a new task.
      consumes:
        - application/json
      parameters:
        - in: body
          name: task
          description: The task to create.
          schema:
            $ref: '#/definitions/Task'
      responses:
        201:
          description: Created.
    get:
      operationId: getAllTask
      summary: Get list of tasks.
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: A list of Tasks
          schema:
            type: array
            items:
              $ref: '#/definitions/Task'
    delete:
      operationId: deleteTask
      summary: Delete task.
      produces:
        - application/json
      parameters:
        - in: body
          name: task
          description: The task to delete.
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: Deleted.
    put:
      operationId: editTask
      summary: Edit task.
      produces:
        - application/json
      parameters:
        - in: body
          name: task
          description: The task with changes.
          schema:
            $ref: '#/definitions/Task'
      responses:
        200:
          description: Edited.

definitions:
  Board:
    type: object
    required:
      - boardId
    properties:
      boardId:
        type: integer
      name:
        type: string
  Column:
    type: object
    required:
      - columnId
    properties:
      columnId:
        type: integer
      name:
        type: string
      boardId:
        type: integer
  Task:
    type: object
    required:
      - taskId
    properties:
      taskId:
        type: integer
      name:
        type: string
      columnId:
        type: integer